// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.113.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.HubSpot.Domain.Test
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;

    using global::FakeItEasy;

    using global::Naos.HubSpot.Domain;
    using global::Naos.Protocol.Domain;

    using global::OBeautifulCode.AutoFakeItEasy;
    using global::OBeautifulCode.Math.Recipes;

    /// <summary>
    /// The default (code generated) Dummy Factory.
    /// Derive from this class to add any overriding or custom registrations.
    /// </summary>
    [ExcludeFromCodeCoverage]
    [GeneratedCode("OBeautifulCode.CodeGen.ModelObject", "1.0.113.0")]
#if !NaosHubSpotSolution
    internal
#else
    public
#endif
    abstract class DefaultHubSpotDummyFactory : IDummyFactory
    {
        public DefaultHubSpotDummyFactory()
        {
            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new AddCompanyRequest(
                                 A.Dummy<IReadOnlyCollection<PropertyModel>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new AddOrUpdateContactsRequest(
                                 A.Dummy<int?>(),
                                 A.Dummy<string>(),
                                 A.Dummy<IReadOnlyCollection<PropertyModel>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new Company(
                                 A.Dummy<IReadOnlyDictionary<string, string>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new Contact(
                                 A.Dummy<IReadOnlyDictionary<string, string>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new CreateAssociationRequest(
                                 A.Dummy<int>(),
                                 A.Dummy<int>(),
                                 A.Dummy<string>(),
                                 A.Dummy<int>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new PropertyModel(
                                 A.Dummy<string>(),
                                 A.Dummy<string>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new UpdateCompanyModel(
                                 A.Dummy<int>(),
                                 A.Dummy<IReadOnlyCollection<PropertyModel>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new AddCompanyOp(
                                 A.Dummy<Company>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetAllCompaniesOp(
                                 A.Dummy<IReadOnlyCollection<string>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new UpdateCompanyOp(
                                 A.Dummy<IReadOnlyCollection<Company>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new AddOrUpdateContactsOp(
                                 A.Dummy<IReadOnlyCollection<Contact>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new GetAllContactsOp(
                                 A.Dummy<IReadOnlyCollection<string>>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new AssociateContactWithCompanyOp(
                                 A.Dummy<int>(),
                                 A.Dummy<int>()));

            AutoFixtureBackedDummyFactory.AddDummyCreator(
                () => new SyncWithHubSpotOp());
        }

        /// <inheritdoc />
        public Priority Priority => new FakeItEasy.Priority(1);

        /// <inheritdoc />
        public bool CanCreate(Type type)
        {
            return false;
        }

        /// <inheritdoc />
        public object Create(Type type)
        {
            return null;
        }
    }
}