// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.75.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.HubSpot.Domain
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Globalization;
    using global::System.Linq;

    using global::OBeautifulCode.Equality.Recipes;
    using global::OBeautifulCode.Type;
    using global::OBeautifulCode.Type.Recipes;

    using static global::System.FormattableString;

    public partial class Contact : IModel<Contact>
    {
        /// <summary>
        /// Determines whether two objects of type <see cref="Contact"/> are equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are equal; otherwise false.</returns>
        public static bool operator ==(Contact left, Contact right)
        {
            if (ReferenceEquals(left, right))
            {
                return true;
            }

            if (ReferenceEquals(left, null) || ReferenceEquals(right, null))
            {
                return false;
            }

            var result = left.Equals(right);

            return result;
        }

        /// <summary>
        /// Determines whether two objects of type <see cref="Contact"/> are not equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are not equal; otherwise false.</returns>
        public static bool operator !=(Contact left, Contact right) => !(left == right);

        /// <inheritdoc />
        public bool Equals(Contact other)
        {
            if (ReferenceEquals(this, other))
            {
                return true;
            }

            if (ReferenceEquals(other, null))
            {
                return false;
            }

            var result = this.Email.Equals(other.Email, StringComparison.Ordinal)
                      && this.Vid.Equals(other.Vid, StringComparison.Ordinal)
                      && this.Properties.IsEqualTo(other.Properties);

            return result;
        }

        /// <inheritdoc />
        public override bool Equals(object obj) => this == (obj as Contact);

        /// <inheritdoc />
        public override int GetHashCode() => HashCodeHelper.Initialize()
            .Hash(this.Email)
            .Hash(this.Vid)
            .Hash(this.Properties)
            .Value;

        /// <inheritdoc />
        public object Clone() => this.DeepClone();

        /// <inheritdoc />
        public Contact DeepClone()
        {
            var result = new Contact(
                                 this.Email?.Clone().ToString(),
                                 this.Vid?.Clone().ToString(),
                                 this.Properties?.ToDictionary(k => k.Key?.Clone().ToString(), v => v.Value?.Clone().ToString()));

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Email" />.
        /// </summary>
        /// <param name="email">The new <see cref="Email" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="Contact" /> using the specified <paramref name="email" /> for <see cref="Email" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002: DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        public Contact DeepCloneWithEmail(string email)
        {
            var result = new Contact(
                                 email,
                                 this.Vid?.Clone().ToString(),
                                 this.Properties?.ToDictionary(k => k.Key?.Clone().ToString(), v => v.Value?.Clone().ToString()));

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Vid" />.
        /// </summary>
        /// <param name="vid">The new <see cref="Vid" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="Contact" /> using the specified <paramref name="vid" /> for <see cref="Vid" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002: DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        public Contact DeepCloneWithVid(string vid)
        {
            var result = new Contact(
                                 this.Email?.Clone().ToString(),
                                 vid,
                                 this.Properties?.ToDictionary(k => k.Key?.Clone().ToString(), v => v.Value?.Clone().ToString()));

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Properties" />.
        /// </summary>
        /// <param name="properties">The new <see cref="Properties" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="Contact" /> using the specified <paramref name="properties" /> for <see cref="Properties" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002: DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        public Contact DeepCloneWithProperties(IReadOnlyDictionary<string, string> properties)
        {
            var result = new Contact(
                                 this.Email?.Clone().ToString(),
                                 this.Vid?.Clone().ToString(),
                                 properties);

            return result;
        }

        /// <inheritdoc />
        public override string ToString()
        {
            var result = Invariant($"Naos.HubSpot.Domain.Contact: Email = {this.Email?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, Vid = {this.Vid?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, Properties = {this.Properties?.ToString() ?? "<null>"}.");

            return result;
        }
    }
}